services:
  couchdb:
    image: couchdb:3.5.1
    ports:
      - "5984:5984"
    environment:
      COUCHDB_USER: "admin"
      COUCHDB_PASSWORD: "admin"
    configs:
      - source: couchdb_ini
        target: /opt/couchdb/etc/local.d/local.ini
    volumes:
      - couchdb_data:/opt/couchdb/data
    restart: unless-stopped

volumes:
  couchdb_data:

configs:
  couchdb_ini:
    content: |
      [couchdb]
      single_node = true

      [chttpd]
      enable_cors = true
      bind_address = 0.0.0.0

      [chttpd_auth]
      secret = couch-auth-secret
      timeout = 600

      [cors]
      origins = *
      credentials = true
      methods = GET, PUT, POST, HEAD, DELETE
      headers = accept, authorization, content-type, origin, referer, x-csrf-token

      [couch_peruser]
      enable = true
      database_prefix = rezero_
      delete_dbs = false
